const PatientActionTypes = {
    GET_ALL_PATIENTS: "GET_ALL_PATIENTS",
    CREATE_PATIENT: "CREATE_PATIENT",
    UPDATE_PATIENT: "UPDATE_PATIENT",
    DELETE_PATIENT: "DELETE_PATIENT",
    CLEAR_DATA: "CLEAR_DATA",
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    SET_SHOW_PATIENT_DIALOG: "SET_SHOW_PATIENT_DIALOG",
    SET_SHOW_ADD_PATHOLOGY_DIALOG: "SET_SHOW_ADD_PATHOLOGY_DIALOG",
    GET_PATIENT_INFO: "GET_PATIENT_INFO",
    SET_SELECTED_PATIENT: "SET_SELECTED_PATIENT",
    GET_PATIENT_BY_ID: "GET_PATIENT_BY_ID"
};

export default PatientActionTypes;
