const PatientActionTypes = {
    GET_ALL_PATIENTS: "GET_ALL_PATIENTS",
    CREATE_PATIENT: "CREATE_PATIENT",
    UPDATE_PATIENT: "UPDATE_PATIENT",
    DELETE_PATIENT: "DELETE_PATIENT",
    CLEAR_DATA: "CLEAR_DATA",
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    SET_SHOW_PATIENT_DIALOG: "SET_SHOW_PATIENT_DIALOG"
};

export default PatientActionTypes;
