const PathologiesActionTypes = {
    GET_ALL_PATHOLOGIES: "GET_ALL_PATHOLOGIES",
    CREATE_PATHOLOGY: "CREATE_PATHOLOGY",
    UPDATE_PATHOLOGY: "UPDATE_PATHOLOGY",
    DELETE_PATHOLOGY: "DELETE_PATHOLOGY",
    CLEAR_DATA: "CLEAR_DATA",
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERRORS",
    SET_SHOW_PATHOLOGY_DIALOG: "SET_SHOW_PATIENT_DIALOG"
};

export default PathologiesActionTypes;
