const AppointmentsActionTypes = {
    GET_ALL_APPOINTMENTS: "GET_ALL_APPOINTMENTS",
    CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
    UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
    DELETE_APPOINTMENT: "DELETE_APPOINTMENT",
    CLEAR_DATA: "CLEAR_DATA",
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERRORS"
};

export default AppointmentsActionTypes;
